import React from "react";
import Head from "next/head";
import { PracticeSass } from "../../components/sass-practice/PracticeSass";
const sassPractice = () => {
  return (
    <div>
      <Head>
        <title>SASS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PracticeSass />
    </div>
  );
};
export default sassPractice;
